import numpy as np

OBS_SHAPE = (6, 5, 2)
OBS_DTYPE = np.float64

GREY_REWARD = - 3
GREEN_REWARD = 20
YELLOW_REWARD = 11
WIN_REWARD = OBS_SHAPE[1] * GREEN_REWARD
WIN_BONUS = 50
LOSE_REWARD = -15
SAME_GUESS_REWARD = - 12
